[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "codex-mini"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.66.0",
    "openai>=1.102.0",
    "prompt-toolkit>=3.0.52",
    "pydantic>=2.11.7",
    "pyyaml>=6.0.2",
    "questionary>=2.1.1",
    "rich>=14.1.0",
    "typer>=0.17.3",
]

[project.scripts]
codex-mini = "codex_mini.cli.main:app"

[tool.hatch.build]
sources = ["src"]

[dependency-groups]
dev = [
    "isort>=6.0.1",
    "pytest>=8.4.1",
]

[tool.hatch.build.targets.wheel.force-include]
"src/codex_mini/core/prompt_codex.md" = "codex_mini/core/prompt_codex.md"
"src/codex_mini/core/prompt_claude_code.md" = "codex_mini/core/prompt_claude_code.md"
"src/codex_mini/core/prompt_init.md" = "codex_mini/core/prompt_init.md"

[tool.ruff]
line-length = 120
