[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "codex-minimal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.102.0",
    "prompt-toolkit>=3.0.52",
    "pydantic>=2.11.7",
    "rich>=14.1.0",
    "textual>=6.1.0",
    "typer>=0.17.3",
]

[project.scripts]
codex-mini = "src.cli.main:main"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[dependency-groups]
dev = [
    "isort>=6.0.1",
]
